"""Build js/demo-data.js from the gigadc-reporting source CSVs.

Usage: python scripts/build_demo_data.py [path-to-gigadc-reporting]

Reads generator/out/{demand,deliveries}.csv and reference/{hierarchy,
model_parameters}.csv, aggregates to Region x month, and writes a small
JS file so the demo works from file:// with no server. Run
`python -m generator` in gigadc-reporting first on a fresh clone.
"""
import csv
import json
import sys
from datetime import date
from pathlib import Path

AS_OF = "2026-09-30"  # default As Of Date parameter in the reports

root = Path(sys.argv[1] if len(sys.argv) > 1 else "../gigadc-reporting")
site = Path(__file__).resolve().parent.parent


def rows(rel):
    with open(root / rel, newline="", encoding="utf-8") as f:
        return list(csv.DictReader(f))


factor = float(rows("reference/model_parameters.csv")[0]["net_supply_factor"])
hierarchy = rows("reference/hierarchy.csv")
region_of = {h["data_center_code"]: h["region"] for h in hierarchy}
area_of = {h["region"]: h["area"] for h in hierarchy}
regions = sorted({h["region"] for h in hierarchy},
                 key=lambda r: next(int(h["region_sort"]) for h in hierarchy if h["region"] == r))

demand = {}
for r in rows("generator/out/demand.csv"):
    demand[(r["region"], r["month_start"][:7])] = float(r["demand_mw"])
months = sorted({m for _, m in demand})

# A building's MW is on its Building Ready row; it counts as supply from
# that row's actual date (planned dates are the baseline, not the outcome).
delivered = {r: {} for r in regions}
for d in rows("generator/out/deliveries.csv"):
    if d["milestone"] == "Building Ready" and d["mw"]:
        m = d["actual_date"][:7]
        reg = region_of[d["data_center_code"]]
        delivered[reg][m] = delivered[reg].get(m, 0.0) + float(d["mw"])

series = {}
for reg in regions:
    cum, sup, dem = 0.0, [], []
    for m in months:
        cum += delivered[reg].get(m, 0.0)
        sup.append(round(cum * factor, 1))
        dem.append(round(demand[(reg, m)], 1))
    series[reg] = {"area": area_of[reg], "supply": sup, "demand": dem}

data = {"asOf": AS_OF, "netSupplyFactor": factor, "months": months,
        "regions": regions, "series": series}
out = site / "js" / "demo-data.js"
out.write_text("// Generated by scripts/build_demo_data.py. Do not edit.\n"
               "window.DEMO_DATA = " + json.dumps(data, separators=(",", ":")) + ";\n",
               encoding="utf-8")
print(f"wrote {out} ({out.stat().st_size:,} bytes, {len(months)} months, {len(regions)} regions)")
