"""Build js/demo-data.js from the gigadc-reporting source CSVs.

Usage: python scripts/build_demo_data.py [path-to-gigadc-reporting]

Reads generator/out/{demand,deliveries}.csv and reference/{hierarchy,
model_parameters}.csv, aggregates to Region x month, and writes a small
JS file so the demo works from file:// with no server. Run
`python -m generator` in gigadc-reporting first on a fresh clone.
"""
import csv
import json
import sys
from datetime import date, timedelta
from decimal import Decimal, ROUND_HALF_EVEN
from pathlib import Path

AS_OF = "2026-09-30"  # default As Of Date parameter in the reports

root = Path(sys.argv[1] if len(sys.argv) > 1 else "../gigadc-reporting")
site = Path(__file__).resolve().parent.parent


def rows(rel):
    with open(root / rel, newline="", encoding="utf-8") as f:
        return list(csv.DictReader(f))


factor = float(rows("reference/model_parameters.csv")[0]["net_supply_factor"])
hierarchy = rows("reference/hierarchy.csv")
region_of = {h["data_center_code"]: h["region"] for h in hierarchy}
area_of = {h["region"]: h["area"] for h in hierarchy}
regions = sorted({h["region"] for h in hierarchy},
                 key=lambda r: next(int(h["region_sort"]) for h in hierarchy if h["region"] == r))

demand = {}
for r in rows("generator/out/demand.csv"):
    demand[(r["region"], r["month_start"][:7])] = float(r["demand_mw"])
months = sorted({m for _, m in demand})

# Port of the Supply and Delivery queries in the Supply and Demand semantic
# model (Delivery.tmdl, Supply.tmdl). Keep the two in step.
def month_of(iso):
    return iso[:7]


def add_day(iso):
    y, m, d = map(int, iso.split("-"))
    return (date(y, m, d) + timedelta(days=1)).isoformat()


def delivery_date(row):
    """When a building's MW counts toward supply (Delivery[Delivery Date])."""
    if row["actual_date"] <= AS_OF:                      # Delivered
        return row["actual_date"]
    if row["planned_date"] > AS_OF:                      # Planned, on schedule
        return row["planned_date"]
    return add_day(AS_OF)                                # Late: day after As Of


def round1(x):
    """Number.Round(x, 1). Decimal avoids binary float ties."""
    return float(Decimal(repr(x)).quantize(Decimal("0.1"), rounding=ROUND_HALF_EVEN))


added = {r: {} for r in regions}
for d in rows("generator/out/deliveries.csv"):
    if d["milestone"] != "Building Ready":
        continue
    m = month_of(delivery_date(d))
    reg = region_of[d["data_center_code"]]
    added[reg][m] = added[reg].get(m, 0.0) + float(d["mw"])

series = {}
for reg in regions:
    cum, sup, dem = 0.0, [], []
    for m in months:
        cum += added[reg].get(m, 0.0)
        sup.append(round1(round1(cum) * factor))         # Supply MW, then Net Supply MW
        dem.append(round(demand[(reg, m)], 1))
    series[reg] = {"area": area_of[reg], "supply": sup, "demand": dem}

data = {"asOf": AS_OF, "netSupplyFactor": factor, "months": months,
        "regions": regions, "series": series}
out = site / "js" / "demo-data.js"
out.write_text("// Generated by scripts/build_demo_data.py. Do not edit.\n"
               "window.DEMO_DATA = " + json.dumps(data, separators=(",", ":")) + ";\n",
               encoding="utf-8")
print(f"wrote {out} ({out.stat().st_size:,} bytes, {len(months)} months, {len(regions)} regions)")
